### ISSUE TITLE
Do More RC4-related ciphers

### ISSUE THREAD

**Issue by DonaldTsang** [andrewarchi/gocipher#2]
There are 20 versions of arc4 in https://eprint.iacr.org/2014/315 which you could try and implement as they are all unique in their own way.

**Comment by DonaldTsang** [comment]
https://github.com/hex7c0/arc4/issues/5

**Comment by thaliaarchi** [comment]
Hello and thanks for using gocipher! You are welcome to submit a PR implementing these RC4 algorithms, but as I no longer actively maintain this repo, I won't be adding these myself.
